version: '3.5'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./data:/prometheus-data
    command: --config.file=/prometheus-data/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100